FROM mxnet/python:nightly_cpu_mkl_py3

USER root

# ENV TRAIN_ON_GPU True

RUN apt update && apt install -y --fix-missing --no-install-recommends \
    build-essential \
    checkinstall \
    make \
    git \
    nginx \
    ca-certificates \
    python3 \
    python3-pip \
    python3-setuptools \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    wget \
    nano

# set working directory
RUN mkdir -p /app
WORKDIR /app

RUN mkdir -p /opt/ml/input/config
RUN mkdir -p /opt/ml/input/data/training
RUN ln -s /opt/ml/input/data/training/ /opt/ml/input/data/testing 
RUN mkdir -p /opt/ml/model
RUN mkdir -p /opt/ml/output
RUN mkdir -p /app/entrypoints

ADD __init__.py .
ADD datasets.py .
ADD net.py .
ADD train.py .
ADD serve.py .
ADD wsgi.py .
ADD nginx.conf .
ADD predictor.py .
ADD technical_indicators.py .
ADD utils.py .
ADD const.py .
ADD settings_base.py ./settings_base.py
ADD settings_dev.py ./settings.py

ADD hyperparameters.json /opt/ml/input/config

ADD experiment_draft.py .

# RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && tar xvf ta-lib-0.4.0-src.tar.gz && cd ta-lib/ && ./configure --prefix=/usr && make && make install

ADD requirements-dev.txt .
RUN pip3 install --upgrade pip
RUN pip install -r requirements-dev.txt

RUN git clone https://github.com/CSTR-Edinburgh/merlin.git && mv merlin merlin_repo && ln -s merlin_repo/src/ merlin && cd merlin_repo && pip install -r requirements.txt

ADD train.sh /app/entrypoints/train
ADD serve.sh /app/entrypoints/serve
RUN chmod +x /app/entrypoints/train /app/entrypoints/serve
ENV PATH=/app/entrypoints:${PATH}

# ENTRYPOINT ["python3","train.py"]
